version: '3'

services:
  bd-zookeeper:
    container_name: bd-zookeeper
    image: wurstmeister/zookeeper
    #restart: on-failure
    ports:
      - "2181:2181"
    networks:
      - bigdatanet

  bd-kafka:
    container_name: bd-kafka
    image: wurstmeister/kafka:2.12-2.5.0
    #restart: on-failure
    ports:
      - "9092:9092"
    environment:
      # 若需要在其它物理主机上访问此Kafka服务，此处应设置为物理主机实际IP地址
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: bd-zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bigdatanet

  bd-mysql:
    container_name: bd-mysql
    build:
      context: ./software/mysql
      dockerfile: Dockerfile
    #restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Bigdata.2020
      MYSQL_USER: bigdata
      MYSQL_PASSWORD: Bigdata.2020
    networks:
      - bigdatanet

  bd-postgres:
    container_name: bd-postgres
    build:
      context: ./software/postgres
      dockerfile: Dockerfile
    #restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Bigdata.2020
    networks:
      - bigdatanet

networks:
  bigdatanet:
